### ISSUE TITLE
[BUG] Ckgedit / ACL

### ISSUE THREAD

**Issue by rmichalowicz** [turnermm/ckgedit#96] opened 2015-06-10 12:39 UTC
Hi everybody,

I try the latest ckgedit version from github (CKEditor 4.4.7 (revision 3a35b3d) _ckgEdit-ckedit_47-15-Jun_01-23_38_ ). I encountered a bug with my users (non-admin users of dokuwiki). My dokuwiki HRUN works under debian wheezy.

Symptoms :
-	When a user wants to make a link (internal media)and explore the server in order to upload some files (like small 50 kb PDF), the listing of directories is empty, the list of files is empty too. So he can’t upload a file and  an access denied popup from ckgedit appeared (« you do not have permission to upload files to this folder. If you think this is incorrect please notify your administrator ») .
-	When the same user try to upload the same file with the media management of dokuwiki there is no problem (ACL Correct)
-	When an admin user try to make the same thing in ckgedit there is no problem. The list of files already present in the directory is presented and the left panel with directories is correct too.

I think there is a bug in ACL management for listing directories and files and consequently uploading files with the latest ckgedit.

Thanks in advance for you answer and thanks for this great work !!
Richard

**Comment by turnermm** [comment] 2015-06-10 14:26
I could not reproduce this bug in my tests, But I did make some changes in the last two commits which might have allowed a bug to creep in.  Try this version:
https://github.com/turnermm/ckgedit/archive/9076b46aa8085f3a128770abe89f118611b93a91.zip
It was the version just prior to the changes.  And please let me know the results.

**Comment by turnermm** [comment] 2015-06-10 14:27
Sorry -- I didn't mean to close this issue.

**Comment by rmichalowicz** [comment] 2015-06-10 15:32
- Same problem with the version  _ckgEdit-ckedit_47-15-May_24-20_02_  I try with  IE11 and latest Google Chrome in the context of the user.
- No problem with dokuwiki admin user

**Comment by turnermm** [comment] 2015-06-10 16:15
Was it working before?  And did you make any changes on youjr server or to your acls?

**Comment by rmichalowicz** [comment] 2015-06-10 16:19
Before i was with fckglite and Adora Belle.
I have upgraded my dokuwiki installation with hrun and the latest plugin. NTLM authentication works fine. There is no modification about URL Rewriting nor Vhost.
Everything works fine except the listing of files and directories with a user context. I will try to make my user an admin in order to test the ACL problem in few seconds (im in production)

**Comment by rmichalowicz** [comment] 2015-06-10 16:22
- When my user was a dokuwiki admin it can list the files and directories for uploading.
- When my user is only a simple user (with rights for upload) it cannot list the files and the panels are blank

**Comment by rmichalowicz** [comment] 2015-06-10 16:29
It seems that the UPLOAD rights only cannot list files and directories
the DELETE rights can do :)

**Comment by turnermm** [comment] 2015-06-10 17:46
That is good news.  I've been testing with the May May_24-20_02 version on Chrome with Debian 7.0 and there were no problems.  I'll install the Jun_01 version and see what I can learn.

**Comment by turnermm** [comment] 2015-06-10 17:54
Installed latest version (_ckgEdit-ckedit_47-15-Jun_01-23_38_ ), @user with upload permission, and was successful.  I didn't need to upgrade the permissions to Delete.  Would it be too much trouble to zip up your ``acl.auth.php`` and ``users.auth.php`` and send them to me at: turnermm02ATshaw.ca?

**Comment by turnermm** [comment] 2015-06-13 02:49
Thank you for the files.  I've looked at them and tested them but the result was the same as before; DELETE rights were not necessary for uploading. It's possible, however, that your active directory settings may be playing a part.  I have no way of testing for that.  But just in case it is something in ckgedit, I  have refactored the code which checks the ACLS, and based it upon the most recent Dokuwiki ACL checks.  It's included in a new test branch:
  https://github.com/turnermm/ckgedit/archive/acl_check.zip
If it is not too much trouble, if you could test that branch, I would be very grateful.

**Comment by turnermm** [comment] 2015-06-13 15:13
Don't Bother with the above.  It turns out that it has bugs.  Sorry.

**Comment by rmichalowicz** [comment] 2015-06-19 16:21
No problem, im alive sorry for the late in news. 
Is there a debug function to log to a File some informations with ckgedit ?

**Comment by turnermm** [comment] 2015-06-19 17:57
That would only be the PHP log file, usually the one used by the web server.  The latest distribution of ckgedit is using the updated acl functions. It seems to be OK. It also fixes broken safe and UTF8 encoding in the file browser. And as an added feature, it enables the user to resize the editor window.

**Closed** 2015-07-10 10:41 UTC
