### ISSUE TITLE
Errors in edit.php

### ISSUE THREAD

**Issue by bighandsFR** [turnermm/ckgedit#135] opened 2016-02-18 22:31 UTC
Hello,

My dokuwiki version is 2014-05-05 "Ponder Stibbons"
My PHP version is 5.2.8.
The uploaded plugin is from 2016-02-17

I Have errors during loading any dokuwiki pages when I try to install your very fine plugin.
I have commented the 3 "if" sections around errors (listed below) to lauch wiki normally.

[18-Feb-2016 22:56:22] PHP Parse error:  parse error in D:\wamp\www\wikiai\lib\plugins\ckgedit\action\edit.php on line 229

[18-Feb-2016 23:11:06] PHP Parse error:  parse error in D:\wamp\www\wikiai\lib\plugins\ckgedit\action\edit.php on line 984

[18-Feb-2016 23:13:17] PHP Parse error:  parse error in D:\wamp\www\wikiai\lib\plugins\ckgedit\action\edit.php on line 1056

Thanks for your job,

Manu

**Comment by turnermm** [comment] 2016-02-19 16:12
The problem is that your version of PHP is out of date.  Dokuwiki now requires PHP 5.3 or later.  There is a fix for this problem but it is not kept up-to-date;  See: 
https://www.dokuwiki.org/plugin:ckgedit#available_versions_of_ckgedit

See: https://www.dokuwiki.org/requirements#php_version_533_or_later

**Closed** 2016-02-23 14:33 UTC
