### ISSUE TITLE
Interwiki-Links with colons seem to be broken again

### ISSUE THREAD

**Issue by RalfWohner-simpleFact** [turnermm/ckgedit#319] opened 2017-08-02 15:30 UTC
Hello there,

first of all, thanks for a great plug-in.

I just tried it out with the default welcome page of a newly installed dokuwiki. Just opening the page and saving (no change done), will replace the colons in interwiki links, so that this:
`Read our [[doku>faq:sidebar|FAQ on sidebars]]`
will become that:
`Read our [[doku>faq%253Asidebar|FAQ on sidebars]]`

If you can, please help.

Thanks!

Ralf

**Comment by turnermm** [comment] 2017-08-03 00:26
That's simply urlencoded.    If no change has been made to the page, then ckgedit does not reprocess the page.

**Comment by RalfWohner-simpleFact** [comment] 2017-08-03 13:08
You are right, I re-checked about "no change done". But the URL encoding happens even if I change anything, not touching the interwiki links at all. The problem is, the URL encoding creates broken (non functional) interwiki links and gets longer every time the page is saved.

Can anything be done to prevent this?

**Comment by turnermm** [comment] 2017-08-03 16:05
I can't reproduce this.  So, it would help if you could give me a step by step description of exactly what you are doing when this happens.  Start from the beginning.

**Comment by turnermm** [comment] 2017-08-03 19:32
OK.  I finally reproduced it.

**Comment by turnermm** [comment] 2017-08-03 19:33
Should be fixed now.

**Comment by turnermm** [comment] 2017-08-03 19:37
Should be fixed in latest update.

**Closed** 2017-08-16 13:08 UTC
