### ISSUE TITLE
CkgEdit  Sidebar Icon has disappeared

### ISSUE THREAD

**Issue by rgleason** [turnermm/ckgedit#515] opened 2020-01-03 18:34 UTC
Please see this post https://forum.dokuwiki.org/post/68038
and this one  https://forum.dokuwiki.org/post/68037

Thought it was connected to bootstrap3 updates, but it does not show using dokuwiki template either.
For awhile I had reverted to an earlier version of bootstrap3 that did not have the page visibility problem and also showed the ckgedit icon in the sidebar, but that situation changed somehow, with the visibility problem showing up again. So I tried upgrading bootstrap3 using the current url, the visibility was fixed but ckgedit icon was gone. Uninstalled and used Dokuwiki template, still the ckgedit icon did not show. Tried uninstall and reinstall of ckgedit and that did not fix it. Tried reinstall of bootstrap3 template, still no ckgedit icon. Tried uninstall and reinstall of ckgedit, still no ckgedit icon.

So I've run out of stuff to do, other than go find that previous version of bootstrap3 that worked, which I may have to do.  Presently using the inferior DWedit.

**Comment by turnermm** [comment] 2020-01-03 22:07
This sounds to me like a caching problem,  caused by bootstrap3, which is where the problem originated.  So, remove all contents from data/cache and delete your browser cache.

**Comment by rgleason** [comment] 2020-01-04 01:03
I've done that now. Cleared data/cache and deleted cache in MS Edge, then logged into OpenCPn wiki.
The ckgedit icon is still missing.
Do you think a configuration setting changed perhaps?

![Screenshot (345)](https://user-images.githubusercontent.com/2363959/71757455-b3b35f00-2e5b-11ea-945d-b82ad926d88e.png)

**Comment by turnermm** [comment] 2020-01-04 04:30
See my comment on the forum: https://forum.dokuwiki.org/thread/17435

**Comment by turnermm** [comment] 2020-01-17 02:13
Fixed.

**Comment by turnermm** [comment] 2020-01-17 02:15
Fixed in dwedit plugin

**Closed by turnermm** 2020-01-17 02:15 UTC

**Comment by rgleason** [comment] 2020-01-17 02:36
Thank you. Myron!
