### ISSUE TITLE
Editor duplicates page contents

### ISSUE THREAD

**Issue by waldauf** [turnermm/ckgedit#343] opened 2017-10-13 11:57 UTC
I'm using CKGEdit like WYSIWYG editor in my DokuWiki. I don't understand how but many times editor duplicates contents of page in the same page. That means I have the same contents two times in the same page. Sometimes it duplicates part of page and sometimes it duplicates all page. It helps to switch to DW editor, remove duplicities and save. In fact I cannot say when it happens and in which conditions. 

# Version

[Bootstrap3 Template] - Last updated on 2016-12-12
[DokuWiki] - Release 2017-02-19e "Frusterick Manners"
[Browser] - Chromium Version 61.0.3163.91
[CKGEdit] - 2017-09-24
[JQuery] -
```
# cat /var/www/lib/scripts/jquery/versions
# this is loaded from the update.sh script and our PHP code
JQ_VERSION=3.1.1
JQUI_VERSION=1.12.1
JQM_VERSION=3.0.0
```

**Comment by turnermm** [comment] 2017-10-13 13:37
Never seen this before. Perhaps it’s something in your configuration.  I suspect the bootstrap template.

**Comment by waldauf** [comment] 2017-10-13 13:52
Yep you're right - I have bootstrap3 template. The problem could be there?

**Comment by turnermm** [comment] 2017-10-13 14:12
I'm not sure, but see what happens if you temporarily switch to the dokuwiki template.  Another possibility is a conflict with another plugin.

**Comment by choosin** [comment] 2017-10-17 03:18
Happen to me everytime I switch editor from CKG to DW (no confirm window shows up but changes being saved directly).
I can see change of duplicating content in history (old revisions).

Installed plugins:
Indexmenu Plugin
Info Plugin
PHP Markdown Extra plugin
Popularity Feedback Plugin
removeold
Revert Manager
safefnrecode plugin
smtp plugin
styling plugin
Wrap Plugin

Templates:
Arctic Template (installed but not selected in configuration manager)

Maybe I have to disable all of them and re-enable one by one to see if any of them really conflicts.

**Comment by turnermm** [comment] 2017-10-17 13:33
Just looking at this I would suspect the markdown plugin.  You are trying to r un two supplementary editors at the same time, these  have generally conflicted with ckgedit.

**Comment by Anonymousdog** [comment] 2017-10-17 21:02
I have this behavior too.  We don't use markdown but do use bootstrap.  Of the above list of extensions, we share only indexmenu, info, popularity feedback, revert, safefnrecode.

This manifests MOST often as an inadvertent save of ckgedit changes it must make when first rendering the editor.  If I select the DWEdit button, these edits are preserved even though I never saved changes.  I have to then revert the page to the previous version before editing (with DWEdit) to fix the page.  It seems like it's nearly always where there are HTML blocks.

**Comment by waldauf** [comment] 2017-10-17 21:11
I don't use markdown also. The problem occurs (what I can see) when I'm editing document and save or  switching between CKGedit and DW edit. In DW edit this problem does not exist.

**Comment by Anonymousdog** [comment] 2017-10-17 21:13
My experience as well.  The content duplication is hard to predict, but the
"mangle and save without clicking save" issue is pretty reliable if there
is ANY special markup (not directly supported by ckgedit) on the page.

**Comment by waldauf** [comment] 2017-10-17 21:16
If I'm thinking about - it happened on bigger documents with some difficult structure - not just text but many headers, some code blocks or tables, .... But as said Anonymousdog it is difficult to predict or simulate.

**Comment by turnermm** [comment] 2017-10-18 01:15
The common element here seems to be boostrap.  That was my first thought, and there's little I can do about that, if that is the source of the problem.

**Comment by KevinMaschke** [comment] 2017-10-19 10:54
I have the same issue. In my case I use the following template on my pages:

```
==== Title ====

----

Content
```

Everytime I switch from CKGedit to DW Editor the line (----) is duplicated.

**Comment by turnermm** [comment] 2017-10-19 14:22
Not the same issue.  That is not the wiki template but a namespace template.  Remove this entry and start a new issue.

**Comment by KevinMaschke** [comment] 2017-10-19 14:55
It's not a namespace template. It's just the content I put in all my pages using DW Editor. Then I save, switch to CKGedit and there I see the Title as Header, with the horizontal line below, and below that,  4 hyphens. It keeps "duplicating" the hyphens everytime I switch from CKGedit to DWEditor.

**Comment by turnermm** [comment] 2017-10-19 15:21
Still not the same issue.

**Comment by KevinMaschke** [comment] 2017-10-19 15:26
To me it sounds like the same waldauf  described:

> The problem occurs (what I can see) when I'm editing document and save or switching between CKGedit and DW edit. In DW edit this problem does not exist.

**Comment by turnermm** [comment] 2017-10-19 23:39
fastwiki
> 
> Conflicts with
>     ckgedit, codemirror, imgpaste, struct
> 
This is something you should have checked for yourself.

**Comment by waldauf** [comment] 2017-10-20 05:54
I'm not using fastwiki and clonning happend to me.

**Comment by turnermm** [comment] 2017-10-20 11:55
Yes,  @waldauf,  but the common thread for you and @Anonymousdog is bootstrap3.

**Comment by KevinMaschke** [comment] 2017-10-20 12:53
Well, the common thread for @waldauf , @Anonymousdog  and me is CKGedit. I don't use bootsrap, and issue persists after uninstalling fastwiki.

**Comment by turnermm** [comment] 2017-10-20 19:00
The common thread of CKGedit is many thousands of users, but only you are  having this particular problem, which, I believe,  is different from the problem of  @waldauf and @Anonymousdog.  I suggest you disable your plugins and reload them systematically to see if you can locate the source in a plugin.  You don't say which browsers  you are using, which OS they run on and which OS your dw runs on.

**Comment by turnermm** [comment] 2017-10-20 19:02
Also, in your diagram, what does `Content` represent?  Because the issue here seems to be in the parser.  And if it is, then simply disabling a plugin is not enough.  You will also have to remove any associated plugin markup.

**Comment by KevinMaschke** [comment] 2017-10-23 11:14
@turnermm  Content is just there for you to know that there is where I place my content. I just use the same template for all my pages, the template being a Header, a horizontal line and then the content.

**Comment by nawaa** [comment] 2017-10-24 16:51
Hi,
I have this behavior too (duplicates part of page in the same page). We don't use nor the markdown plugin nor the bootstrap template. We use few plugins, none of these plugins has known conflicts with another : ckgedit, discussion plugin, Dw2Pdf plugin, edittable, Move plugin. All of them are certified compatible with Frusterick Manners Dokuwiki, except Move. But even with Move disabled, the bug occurs.
It happens often when switching between CKGedit and DW edit, but not only : most of the users only use CKGedit, never switching to DW, and regularly meet this bug.
The first reported occurrence of this bug on my instance is 2017-10-02.
Having all plugins up-to-date (that wasn't the case at the beggining of the month) doesn't solve anything.
The dokuwiki runs on a Debian jessie, browsers and OS used are multiple (I use up-to-date Firefox and Debian, other users use Firefox, Chrome, IE, Safari with Windows or MacOS, with various versions, as it is widely used by an association).

**Comment by turnermm** [comment] 2017-10-24 19:15
Try this: 
  https://github.com/turnermm/ckgedit/archive/Sep_20a.zip.
It takes you back a few updates ago, before the date at which you say you had this problem.  If it stops, I will know where to start looking.  So, I'd appreciate knowing the result.

**Comment by turnermm** [comment] 2017-10-24 19:26
>  use up-to-date Firefox and Debian, other users use Firefox, Chrome, IE, Safari with Windows or MacOS, with various versions, as it is widely used by an association).

Does it happen in all of these browsers and systems of just certain ones?

**Comment by turnermm** [comment] 2017-10-24 19:59
@nawaa, on which version of debian are you running your dokuwiki?

**Comment by turnermm** [comment] 2017-10-24 21:45
@waldauf and @Anonymousdog do either of you have an idea as to when these problems started?

**Comment by nawaa** [comment] 2017-10-25 09:28
@turnermm thanks for your quick answer.
I will try with the archive that you propose, but actually my version was older. I have been silly enough to not note the exact version before updating it for debugging, I only know it was after beginning of march 2017 (when I applied the fix regarding a bug converting internal links into external ones). I don't remember the exact moments when I updated the plugin after that. Anyway, I gave the date of the first known occurrence of the bug, but I can't find a link between this date and a former update (regarding Dokuwiki or the server).
Regarding navigator and OS, two users have reported the bug, one with Chrome and Windows, the other with Firefox and Windows (I can ask the exact versions if needed). Both of them never switch from CKG to DW, and don't really know when it occurs.
On my side, I use Firefox 52.3.0 and Debian Jessie 8.9 (not so up-to-date actually ;-)). I can quite easily reproduce the bug when switching between CKG and DW, in two cases: when there is an audio file or when there is a large number of headers (as already noted by @waldauf).
The Dokuwiki runs on a Debian Jessie 8.9.

**Comment by waldauf** [comment] 2017-10-25 10:02
@turnermm I have new and fresh installation of DW in docker container, running on Alpine Linux. I just created some pages with rules for my company defining how to work with DW. My browser is Chromium. There are problems with duplicities of pages from begenning.

Now I don't belew it is caused by bootstrap3 templete. If yes so boostrap3 issues tracking system would be full of reported problems.

**Comment by nawaa** [comment] 2017-10-25 10:03
More precisely about occurrences: when there is an audio file, a simple CKG edit of the page duplicates the audio file systematically (without even switching between CKG and DW). When there is numerous headers, the bug occurs erratically (it was quite systematic yesterday, I can't reproduce it today without any other change).

**Comment by Anonymousdog** [comment] 2017-10-31 16:12
Sorry about the late reply: I have had these symptoms since I first
installed ckgedit late this Summer.

Andy

**Comment by turnermm** [comment] 2017-10-31 17:19
This thread is not going anywhere, unfortunately.  #KevinMaschke 's problem is in the parser, similar to these: https://github.com/turnermm/ckgedit/issues/345, https://github.com/turnermm/ckgedit/issues/344, which are usually quickly solved because, once all the data is in, consistently reproducible.  But the problem the other users are having lies somewhere in the system on which the wiki is running and is not consistently reproducible.  If I'm going to solve this I'll need more info.  I've tested bootstrap3, I've tested debian with no result.  It would help to know, for instance, what kind of resources your system  has--i.e. are you running a stand-alone linux or Windows machine, are you running on a vps, or on a hosted shared system where you are one of many users?  Can you check your system error logs to see possibly relevant error messages?  What version of php are you using? Are you using apache or another web server setup?  Any information of this sort would be helpful.

**Comment by Anonymousdog** [comment] 2017-11-06 21:24
Ubuntu Server 16.04 LTS with PHP 7.0, Apache 2.4.18. (also produced on
14.04 with PHP 5.6, Apache 2.4.x).  I can reproduce it on AWS VMs, VMWare
VMs, and installed straight on hardware.  So, those computer resources are
all over the board (2 cores to 8, 1GB RAM to 16, SSD to HDD).  I've never
seen apache errors logged in concert with the behavior (but I'll try to
make some time to check).

We appreciate all your work.

Thanks,
Andy

**Comment by waldauf** [comment] 2017-11-06 21:46
My configuration:

- Host OS: CentOS Linux 7, virtual machine (from some hosting farm)
- Guest OS: Alpine Linux 3.6.2 running in Docker
- Nginx server: 1.12.1
- PHP: 7.1.10
- Browser: Chrome (latest version)


My  Nginx configuration:
```
server {
        listen 80;

        root /var/www;
        index index.php index.html index.htm;

        client_max_body_size 40M;
        client_body_buffer_size 128k;

        location / {
            index doku.php;
            try_files $uri $uri/ @dokuwiki;
        }

        location @dokuwiki {
            rewrite ^/_media/(.*) /lib/exe/fetch.php?media=$1 last;
            rewrite ^/_detail/(.*) /lib/exe/detail.php?media=$1 last;
            rewrite ^/_export/([^/]+)/(.*) /doku.php?do=export_$1&id=$2 last;
            rewrite ^/(.*) /doku.php?id=$1 last;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass unix:/var/run/php-fpm7.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.ht {
            deny all;
        }

        location ~ /(data|conf|bin|inc)/ {
            deny all;
        }
    }
```

In log I don't see any errors. During week I tried to increase log level. I'll try to find out conditions when content is duplicated. 

As said @Anonymousdog we appreciate your work and help.

**Comment by turnermm** [comment] 2017-11-07 00:28
This is just a shot in the dark.  Is the issue ever associated with the draft message:
`"This document has a draft file. The draft button toggles between the this document and the draft. You can edit and save either of the two." ;
`

**Comment by nawaa** [comment] 2017-11-07 10:30
Not for me, never.
Have you tried with an audio file? The bug occurs systematically in that case for me.
Thanks for your help!

**Comment by waldauf** [comment] 2017-11-09 08:44
@turnermm I have small idea. I'm running my DW in container so if you want I can send you my all DW.

**Comment by turnermm** [comment] 2017-11-09 10:47
@waldauf  that could be very helpful.  @nawaa, I do not get your result when using audio files, unless perhaps you have the audio files set to run when in the editor, which is something I have no experience with.

**Comment by turnermm** [comment] 2017-11-09 10:55
@nawaa, I just tried running an audio file in the editor and switcing over to dwedit -- no success.

**Comment by Anonymousdog** [comment] 2017-11-10 01:49
Not certain.  I do know I've seen those draft messages where I know a draft
shouldn't exist (e.g., right after an edit save).

I do see duplicates of content where there is plugin syntax not directly
supported by ckgedit (probably parser issues), but I also see erroneous
saves of edits not made when switching editors (and that symptom is often
followed by the editor declaring a draft as available [after that erroneous
edit]).

I'd be willing to develop a VMware VM that exhibits symptoms and send you
the whole VM. Can't send the data in these production wikis though.

Thanks again,
Andy

**Comment by waldauf** [comment] 2017-11-12 22:12
@turnermm I have prepared my DokuWiki image. Can you give me your email I'll send you there URL for downloading.

**Comment by turnermm** [comment] 2017-11-13 03:09
See the header to ckgedit/action/edit.php.  But I'm not sure I will  be able to run it.  I have a mac laptop with Parallels which might be able to do it or I might be able to convert it for use with the KVM system which I run.

**Comment by waldauf** [comment] 2017-11-13 09:22
@turnermm Don't be affraid. It's not virtual system but just Docker image. ;] You need:

1. [Download](https://docs.docker.com/compose/install/) Docker and docker-compose for MacOS.
2. Download my zip file - I'll send you share link to your email, and unizp it.
3. Read README.txt which is in zip file and you'll proceed according it. And run docker image.
4. You can test my DW setting with all plugins. A kept there some pages (in czech) which you can modify as you want. You can browse all directory structure without problem and modify it directly on your disk. 

If you wish we can make it together. It depends on time which we agree. ;]

**Comment by waldauf** [comment] 2017-11-13 17:29
May be we're thinking to slow and huge. :]] I realized that I just send you my DW and you will run it in your computer with Nginx/Apache/whatever and it should work. You don't need any Docker engine. ;]

**Comment by turnermm** [comment] 2017-11-14 02:19
That's a vary good idea.

**Comment by waldauf** [comment] 2017-11-14 10:14
Please write me email on "wwwaldauf" on google. I'll send you shared URL. ;]

**Comment by turnermm** [comment] 2017-11-14 14:58
Write to you @google.com bounced.

**Comment by waldauf** [comment] 2017-11-17 11:51
Now I'm little bit lost. Till now I haven't gotten any email from you.

**Comment by turnermm** [comment] 2017-12-31 20:19
A user of ckgdoku sent me files which cause duplication and I believe I've found the problem.  So, if you are still using ckgedit, you can try:  
    https://github.com/turnermm/ckgedit/archive/dwed.zip
Please let me know your results.  If all goes as I hope, I will merge this fix into the master.

**Comment by turnermm** [comment] 2018-01-01 21:08
This is same  issue as https://github.com/turnermm/ckgdoku/issues/48, which has been successfully tested, and so I am closing this ckgedit issue as fixed.

**Closed by turnermm** 2018-01-01 21:08 UTC
