### ISSUE TITLE
CKGEdit wysiwyg editor breaks <code> tag

### ISSUE THREAD

**Issue by mirakrejci** [turnermm/ckgedit#612] opened 2021-03-09 11:39 UTC
When a page contains the "code" tag, the CKGEdit wysiwyg editor breaks the formatted content. In the wysiwyg editation view, the "code" tag is kept in place but line breaks are not respected which obviously breaks the internal code.

The problem occurs every time the selected section of the page that contains the "code" tag is edited and then the section is saved (either with the SAVE or DW EDIT button.

If the entire document is edited, the problem only occurs if the DW EDIT button is used for saving.

**Comment by turnermm** [comment] 2021-03-09 13:56
I really don't follow this.  Why are you inserting code tags into the ckgedit's editor?  Use the code tool.

**Comment by turnermm** [comment] 2021-03-09 15:10
I did several tests, following your process as described above, and can't reproduce this.  

Does this happen whether or not you are editing the text inside the code block?  Or only when you are editing inside the code block?  If the latter, then see what happens if you remove the code block before making the edits, and then reapply the code block after the edits are made.

**Comment by turnermm** [comment] 2021-03-10 19:55
I have never seen this problem myself and even in your own case the problem is not constant.   That makes it impossible for me to work with.  If you could give me a scenario where it always happens, I could then try to determine the cause.  At a minimum you could tell me which server your dokuwiki is on, which browsers this happens in and on which OSes do they run.  Are there any javascript errors showing in the browser consoles?  Do you find any errors in your server logs?

**Comment by mirakrejci** [comment] 2021-03-11 13:08
O.K. I'll try find a scenario where it always happens. In the described scenario, however, it happens to me mostly. 
I've seen no javascript errors in the browser consoles. Also no errors I can find in Apache error log.

Chromium version 87.0.4280.66 (Official Build) Built on Ubuntu
Firefox 86.0 (64bit). 
client OS: Ubuntu 18.04 (64-bit) - system up to date

Server version: Apache/2.4.6 (CentOS)
DokuWiki version: Release 2020-07-29 "Hogfather"
PHP version 7.2.34
CKGEdit version: 2021-02-23

**Comment by mirakrejci** [comment] 2021-03-11 16:07
I'm sending a complete page opened at DW edit:
[page.txt](https://github.com/turnermm/ckgedit/files/6124236/page.txt)

Please have CKG as the default editor before you start testing.
You can use the same scenario which I described during creating the issue. The problem always occurred regardless of whether I used Chromium or Firefox.
It also always occured on Windows (Chrome and MS Edge).

Windows 10, build 19042.685
Chrome 88.0.4324.190
Edge 89.0.774.48 (64bit)

Page view before:
![before](https://user-images.githubusercontent.com/41993122/110816268-7b8f8380-828b-11eb-91fb-76b40e203928.png)

and after saving:
![after](https://user-images.githubusercontent.com/41993122/110816396-97932500-828b-11eb-9195-e51a9ae87ff7.png)

Thanks!

**Comment by turnermm** [comment] 2021-03-12 00:24
Was closed by mistake.  Above is a brief video showing my results, using windows 10 and firefox.

**Comment by mirakrejci** [comment] 2021-03-12 10:19
The video shows that you are editing the entire page and then saving it with the SAVE button, which is exactly the case when the problem does not manifest itself.

The problem manifests itself if you save the document by pressing **DW EDIT** instead of **SAVE**.
If you edit **only the selected section** of the page (which contains the code tag), the error will manifest itself in both cases (SAVE and DW EDIT button). I have already stated this when creating the issue.

**Comment by turnermm** [comment] 2021-03-12 15:34
What you said is this:

> The problem occurs every time the selected section of the page that contains the "code" tag is edited and then the section is saved (**either with the SAVE or DW EDIT button.**


Now I've tried every which way to get your result and have not been able to reproduce it.  Making changes to the text, hitting SAVE, hitting DW Edit, etc.  Loading only the section with the code block, loading the whole page.  If it's a deal-breaker for you then don't use ckgedit.

**Closed by turnermm** 2021-03-12 15:34 UTC

**Comment by mirakrejci** [comment] 2021-03-15 10:07
You write don't use CKGedit, but there is no better wysiwyg editor for Dokuwiki. Not using CKGedit means (due to most users) not using Dokuwiki.
I know you've already closed the case. I'm sorry, but I'm still sending videos, in case we misunderstood. 

https://user-images.githubusercontent.com/41993122/111136530-22229f80-857e-11eb-8ad2-eb93d2353fa0.mp4

https://user-images.githubusercontent.com/41993122/111136536-23ec6300-857e-11eb-9c95-f30a8f5806bf.mp4

**Comment by turnermm** [comment] 2021-03-16 00:03
It doesn't do me any good to show me your result, since I can't reproduce it, as my video shows.  I see you are using the publish plugin, maybe that interferes somehow with ckgedit.  Not likely, but plugin incompatibility is one possibility.   Disable all plugin which you installed and see if this happens.  If not, then reenable them one at a time and see which is the cause.

**Comment by mirakrejci** [comment] 2021-03-16 09:50
Thank you for your idea of disabling all other plugins. The conflict is with the codeprettify plugin. Even the same bug is pointed out here: [https://github.com/ssahara/dw-plugin-codeprettify/issues/13]
There is no reaction, there is probably nothing to do with it (except disabling codeprettify).

Thank you very much!
