### ISSUE TITLE
Issue with the full screen

### ISSUE THREAD

**Issue by GalgenAndi** [turnermm/ckgedit#300] opened 2017-05-27 20:56 UTC
Hello,

I have found an error in youre plugin.
From a size of 8,766 characters, the menu bar disappears.
I use the CKE editor very gladly and would be glad about a solution.

Please excuse my bad English.

Many thanks in advance.

Best regards
Andreas

Screenshots
========
Normal (over 8,766 characters): [http://www.directupload.net/file/d/4734/nzw4ipgh_jpg.htm](http://www.directupload.net/file/d/4734/nzw4ipgh_jpg.htm)
Full View (under 8,766 characters): [http://www.directupload.net/file/d/4734/geanyc7k_jpg.htm](http://www.directupload.net/file/d/4734/geanyc7k_jpg.htm)
Full View (over 8,766 characters): [http://www.directupload.net/file/d/4734/owltcoqj_jpg.htm](http://www.directupload.net/file/d/4734/owltcoqj_jpg.htm)
Notepadd++ (Without error on Wiki): [http://www.directupload.net/file/d/4734/gqwob3tm_jpg.htm](http://www.directupload.net/file/d/4734/gqwob3tm_jpg.htm) 
Notepad++ (With error on Wiki): [http://www.directupload.net/file/d/4734/44xuvyhc_jpg.htm](http://www.directupload.net/file/d/4734/44xuvyhc_jpg.htm)

DokuWiki 
======
Version: Release 2017-02-19b "Frusterick Manners"

Plugin CKGEDIT
======
Installed version: 2017-05-19
The lats Update: Sat, 27 May 2017 22:01:20 +0200

PC
======
Browser: Firefox 53.0.3
OS: Windows 7 Professional 64-bit

Software
======
Apach friends XAMPP 5.5.37
PHP Version 5.5.37

**Comment by turnermm** [comment] 2017-05-27 22:16
This is a problem in Firefox  and Ckeditor.  It does not happen in Chrome or Opera.  I'm afraid there is nothing I can do about it.  If you want to use the full screen mode you will have change to one of these other browsers.  Possibly when CKEditor 5.x is ready, this problem will disappear.

**Comment by turnermm** [comment] 2017-05-28 00:40
I have been experimenting with different options and settings.  Then I thought I would try a different template.  The bootstrap3 template works in Firefox with the full screen editor.  So the problem is a combination of firefox and the dokuwiki template.  The simple_sidebar template, which I wrote some years ago, also works. So, try different templates, and if you do, please let me know what you find.

 I hope this helps.

**Comment by turnermm** [comment] 2017-07-31 14:13
Ckgedit has just upgraded the CKEditor from version 4.51 to 4.7 and the problem you were having seems to  have been fixed in 4.7.

**Closed** 2017-08-03 00:29 UTC
