### ISSUE TITLE
Uncaught Parse Error by pasting from google spreadsheet

### ISSUE THREAD

**Issue by vikbez** [turnermm/ckgedit#219] opened 2016-07-01 13:09 UTC
There is a 

```
Uncaught Parse Error: <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Rom&quot;}" class="col0">foo</td> ...
```

when pasting from a google spreadsheets document;

The parse error comes from the `-` in the attribute name `data-sheets-value`: if the attribute is removed or replaced for example with `datasheetsvalue` then this works perfectly.

**Comment by turnermm** [comment] 2016-07-01 13:27
There are no guarantees when pasting from HTML documents.

**Comment by drasco** [comment] 2018-10-08 06:49
The issue is hyphens in the attribute name.

The fix is in the regex - \w becomes inclusive of the hyphen - [\w-]

startTag = /^<(\w+)((?:\s+[\w-](?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,
attr = /([\w-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g;

**Comment by turnermm** [comment] 2018-10-08 16:08
That's John Resig's code.  So you might want to get in touch with him.  But I'm not ready to second-guess him, since I am not sure what the unintended consquences of that change might be, though on the face of it, it may look harmless.

**Comment by cpholt** [comment] 2019-12-05 21:01
Came here after spending an hour finding the same bug and the same solution.  I also came across other people who had made the same fix in other projects.

**Comment by turnermm** [comment] 2019-12-05 21:47
Please test this: https://github.com/turnermm/ckgedit/archive/attr_hyphen.zip and see #509.  Thanks.

**Comment by cpholt** [comment] 2019-12-05 21:54
Wow, thanks for the fast response.  I'll test tomorrow when in the office
and let you know.

**Comment by cpholt** [comment] 2019-12-06 13:19
That fix works here.

btw, the use case in the original ticket was a google sheets copy/paste.
For me it was copy/paste from a table in Confluence (one of the worst
editors I've ever tried to use).  Dokuwiki + your editor is lightyears
ahead of them.

Thank you!

**Comment by turnermm** [comment] 2019-12-06 15:13
I was worried about any unintended side-effects from the change.  Regular expressions, especially in ones that complex can sometimes be tricky. I had already made one work-around for html5 attributes at lines 85ff.

I'll merge this fix into the master.  If something breaks, I'll hear about it soon enough.
Thanks.

**Comment by cpholt** [comment] 2019-12-06 15:19
Yeah, regex make my head hurt and I've been doing them for 20 years :).

You probably already know of this or a similar tool, but this is one of my
favorite regex tools.  https://regex101.com/.  It helps make them hurt
less...

**Comment by turnermm** [comment] 2019-12-09 14:55
I merged this fix this morning.  Thanks.

**Closed by turnermm** 2019-12-09 14:56 UTC
