### ISSUE TITLE
Blockquote?

### ISSUE THREAD

**Issue by trapexit** [turnermm/ckgedit#514] opened 2019-12-29 05:00 UTC
Any good way to add a blockquote button? The ckgedit blockquote plugin appears to have the tags stripped on save. The doku blockquote plugin works with literal blockquote tags in the text but that's not as nice obviously.

**Comment by turnermm** [comment] 2019-12-30 00:54
I assume you have installed the CKEditor blockquote plugin.  If so, you could use the CKEditor blockquote plugin/and button enclose the blockquoted text like this:
```
~~START_HTML_BLOCK~~

   block  starts here
    ends here

~~CLOSE_HTML_BLOCK~~
```
I'm not sure this is what you want.  But it recognizes Dokuwiki text formatting, lists, links, images, headlines, etc.

**Comment by trapexit** [comment] 2019-12-30 03:38
Doesn't seem to be working for me but with the dokuwiki blockquote plugin I can just use that. Not WYSIWYG but works.

**Comment by turnermm** [comment] 2020-01-06 17:24
I've included the blockquote feature.  The icon (quotation marks) is in the final row of the toolbar:
![2020-01-06 11_13_57-✎ playground_blockquote3  mturner org](https://user-images.githubusercontent.com/176447/71834883-e5077700-3075-11ea-8d2a-59a268aec5db.png)
This requires the dokuwiki blockquote  plugin.  And to have the same blockquote appearance in the editor as in the browser, you have to run the `CKEditor editor CSS tool` which you will find on the Admin page.  Check off both checkboxes, to `include the blockquote styles` and to `copy to ckeditor/css.`

This ended up taking a fair bit of time, so I would greatly appreciate feedback.  Thanks.

**Comment by turnermm** [comment] 2020-01-06 17:28
Sorry.  Forgot to give you the link:  https://github.com/turnermm/ckgedit/archive/blockquote.zip
It's not yet merged into the master branch.

**Comment by trapexit** [comment] 2020-01-06 17:55
The appearance in the editor doesn't appear to be working. I enabled "plugin>ckgedit>style_sheet" and generated the _style.css file. I see the blockquote entry both in the file and on the page:
![image](https://user-images.githubusercontent.com/197676/71837180-cd36ef80-3083-11ea-9ad3-6a01ba16bd44.png)

**Comment by turnermm** [comment] 2020-01-06 18:58
> I see the blockquote entry both in the file and on the page.

I don't understand this.  In any event, your css6.php seems to be from an earlier version.  The current css6 eliminates the `blockquote-class` class and all of the secondary blockquote plugin elements, like `cite.`  I just installed ckgedit in another test wiki from this url:  https://github.com/turnermm/ckgedit/archive/blockquote.zip (same as above).  There were no problems.

This update requires the complete replacement of the previous ckgedit.
[ckgedit-blockquote.zip](https://github.com/turnermm/ckgedit/files/4027405/ckgedit-blockquote.zip)
I am attaching the upgrade.

**Comment by trapexit** [comment] 2020-01-06 19:17
Perhaps I'm doing something wrong.

- unzip ckgedit-blockquote.zip
- mv ckgedit-blockquote ckgedit
- cp ckgedit blockquote plugin to ckgedit/ckeditor/plugins
- add "Blockquote" to plugin»ckgedit»extra_plugins
- enable plugin»ckgedit»style_sheet
- generate the CSS _style.css file

**Comment by trapexit** [comment] 2020-01-06 19:47
Figured out the problem. ckeditor.js is making the path for _style.css equal http://lib/plugins/ckgedit/ckeditor/css/_style.css. Trying to track down why.

**Comment by trapexit** [comment] 2020-01-06 20:55
alt_style_sheet() in edit.php has a prefix '/' that is causing an issue when DOKU_BASE = '/'

**Comment by turnermm** [comment] 2020-01-06 23:43
That's good to know  I;m hoping it's working for you now, so you can give me your view of whether or not the Button should automatically be installed.

**Comment by trapexit** [comment] 2020-01-07 10:30
Might be worth it. There does appear to be some quirks. Not sure how it should be hanleded but for instance: toggle blockquote on a heading (h2 in this case). It looks to render correctly in the editor but when saved it is the raw "== heading ==" in the blockquote. If I then re-edit the heading is now outside the blockquote. But for the average usecase it seems to be working fine.

In the least the alt_style_sheet() function should be fixed for those who have doku installed at the base directory.

**Comment by turnermm** [comment] 2020-01-07 13:43
> blckquote on a heading (h2 in this case). It looks to render correctly in the editor but when saved it is the raw "== heading =="

That is because the blockquote plugin does not accept headings.

**Comment by trapexit** [comment] 2020-01-07 15:59
I don't know enough about the app to know if it has the ability to forbid incompatible behaviors. I was just pointing out a rendering and behavior quirk.

**Comment by turnermm** [comment] 2020-01-08 22:11
> I'm not quite sure what you're asking when you asked if it should be included by default. 

By default, i.e. included as part of the standard features and therefore standard toolbar, like lists, etc.   Which it now is, so you don't have to include the plugin name in the extra plugins boc of the Configuration Manager.  And it's no longer necessary to update the CSS with the CCC tool, since the needed CSS is already included by default.  However, if your change your template and create a _style.css, the blockquote css will be included.  The only extra thing that the admin has to do is to include the blockquote plugin.

The test url is still the same.

**Comment by trapexit** [comment] 2020-01-09 15:21
Sorry. What I meant was I didn't know if you were asking for my opinion on if it is useful (which would be "yes") or if you were asking if I thought it was in a good enough state to be included by default ... hence my pointing out the quirks in case you wanted to do something about them before adding the feature generally. Either way I think it's a good addition regardless of the quirks.

**Comment by turnermm** [comment] 2020-01-10 15:42
This is pretty much finished.  The blockquote styling is handled  by two css files named `additonal.css`, one in `ckgedit/ckeditor` and one in  `ckgedit/ckeditor/css`.  Normally these will have the same code and normally they will reflect the blockquote css output by dokuwiki.  One of the benefits of these css files is that their effects are not limited to blockquotes.  By designating the css for an element as `!important` you can override any other settings. So now you just load ckgedit and the blockquote plugin and you are ready to go.

**Comment by turnermm** [comment] 2020-01-18 16:09
This has been merged into  the master

**Closed by turnermm** 2020-01-18 16:09 UTC
